name : Docker Deploy

on:
  push:
    branches:
      -main

jobs : 
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
      uses : actions/checkout@v2

      - name ; Login o Docker Hub
      run: docker login -u ${{ secrets.vinisiri }} -p ${{ secrets.pd9@wzmnhun31 }}

     - name : Build and push Docker image
      run : |
        docker build - t my-react-native-app
        docker tag my-react-native-app ${{ secrets.vinisiri }}/my-react-native-app:latest
        docker push ${{ secrets.vinisiri }}/my-react-native-app:latest}}