# name: Docker Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}

#       - name: Build and push Docker image
#         run: |
#           docker build -t my-react-native-app -f Dockerfile.dev .
#           docker tag my-react-native-app ${{ secrets.DOCKERHUB_USERNAME }}/my-react-native-app:latest
#           docker push ${{ secrets.DOCKERHUB_USERNAME}}/my-react-native-app:latest
name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: Build and push Docker image
        run: |
          docker build -t my-react-native-app -f Dockerfile.dev .
          docker tag my-react-native-app ${{ secrets.DOCKERHUB_USERNAME }}/my-react-native-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/my-react-native-app:latest

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name my-react-native-container ${{ secrets.DOCKERHUB_USERNAME}}/my-react-native-app:latest
        ports:
          - 8080:80
