name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug Password
        run: echo "DOCKER_PASSWORD is ${{ secrets.DOCKER_PASSWORD }}"
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.vinisiri}} -p ${{secrets.vinaysirige}}
        
     

      - name: Build and push Docker image
        run: |
          docker build -t my-react-native-app .
          docker tag my-react-native-app ${{ secrets.vinisiri }}/my-react-native-app:latest
          docker push ${{ secrets.vinisiri }}/my-react-native-app:latest
