name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.react }} -p ${{ secrets.react_testing }}

      - name: Build and push Docker image
        run: |
          docker build -t my-react-native-app .
          docker tag my-react-native-app ${{ secrets.react }}/my-react-native-app:latest
          docker push ${{ secrets.react }}/my-react-native-app:latest
